apiVersion: batch/v1
kind: Job
metadata:
  generateName: awave-basic-
spec:
  completions: 1
  backoffLimit: 1
  ttlSecondsAfterFinished: 1800
  template:
    metadata:
      name: awave-pod
    spec:
      activeDeadlineSeconds: 300
      containers:
      - name: run
        image: $container
        command:
          - bash
          - -c
          - >-
            $(KGPU_SUBMIT_DIR)/build-dev/awave
            -shape 1024,1024,1024 -nsteps 100 -out_period 100
            $(KGPU_JOB_NAME) > $(KGPU_JOB_NAME).log
        resources:
          requests:
            cpu: 4
            memory: 32Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 8
            memory: 32Gi
            nvidia.com/gpu: 1
      restartPolicy: Never
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
